 #include "config.h" 

#include <locale.h> 
#include <stdio.h> 
                           #include <string.h> 
#include <libxml/encoding.h> 
#include <libxml/xmlwriter.h> 
#include <glib/gi18n.h> 

int 
main (int argc, char* argv[]) 
{ 
  setlocale (LC_ALL, argv[2]); 
  bindtextdomain (GETTEXT_PACKAGE, "locale");
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE); 

  xmlTextWriterPtr writer; 
                     xmlChar *tmp; 

  writer = xmlNewTextWriterFilename (argv[1], 0); 
  xmlTextWriterStartDocument (writer, NULL, "utf-8", NULL); 
  xmlTextWriterStartElement (writer, "strings"); 
xmlTextWriterStartElement (writer, "GOOGLE_GADGETS");
xmlTextWriterWriteString (writer, _("Gadgets"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "API_VERSION");
xmlTextWriterWriteString (writer, _("(API Version: %s)"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "GGL_COPYRIGHT");
xmlTextWriterWriteString (writer, _("Copyright © 2009 Google Inc. All Rights Reserved.&#10;Licensed under the Apache License, Version 2.0:"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "GGL_DESCRIPTION");
xmlTextWriterWriteString (writer, _("For more information please visit our project site:"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "TIME_FORMAT_SHORT");
xmlTextWriterWriteString (writer, _("%I:%M%P"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "DATE_FORMAT_SHORT");
xmlTextWriterWriteString (writer, _("%b %d"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "DAY_AGO_SHORT");
xmlTextWriterWriteString (writer, _("%dd ago"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "DAYS_AGO_SHORT");
xmlTextWriterWriteString (writer, _("%dd ago"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "DAY_AGO_LONG");
xmlTextWriterWriteString (writer, _("%d day ago"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "DAYS_AGO_LONG");
xmlTextWriterWriteString (writer, _("%d days ago"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "HOUR_AGO_SHORT");
xmlTextWriterWriteString (writer, _("%dh ago"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "HOURS_AGO_SHORT");
xmlTextWriterWriteString (writer, _("%dh ago"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "HOUR_AGO_LONG");
xmlTextWriterWriteString (writer, _("%d hr ago"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "HOURS_AGO_LONG");
xmlTextWriterWriteString (writer, _("%d hrs ago"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "MINUTE_AGO_SHORT");
xmlTextWriterWriteString (writer, _("%dm ago"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "MINUTES_AGO_SHORT");
xmlTextWriterWriteString (writer, _("%dm ago"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "MINUTE_AGO_LONG");
xmlTextWriterWriteString (writer, _("%d min ago"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "MINUTES_AGO_LONG");
xmlTextWriterWriteString (writer, _("%d mins ago"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "OPEN_CONTENT_ITEM");
xmlTextWriterWriteString (writer, _("Open"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "REMOVE_CONTENT_ITEM");
xmlTextWriterWriteString (writer, _("Remove"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "DONT_SHOW_CONTENT_ITEM");
xmlTextWriterWriteString (writer, _("Don't show me items like this"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "VD_BACK_BUTTON_TOOLTIP");
xmlTextWriterWriteString (writer, _("Previous"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "VD_FORWARD_BUTTON_TOOLTIP");
xmlTextWriterWriteString (writer, _("Next"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "VD_POP_IN_OUT_BUTTON_TOOLTIP");
xmlTextWriterWriteString (writer, _("Toggle Expanded View"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "VD_MENU_BUTTON_TOOLTIP");
xmlTextWriterWriteString (writer, _("Menu"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "VD_CLOSE_BUTTON_TOOLTIP");
xmlTextWriterWriteString (writer, _("Remove"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "SIDEBAR_ADD_GADGETS_TOOLTIP");
xmlTextWriterWriteString (writer, _("Add gadgets"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "SIDEBAR_MENU_BUTTON_TOOLTIP");
xmlTextWriterWriteString (writer, _("Menu"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "SIDEBAR_MINIMIZE_BUTTON_TOOLTIP");
xmlTextWriterWriteString (writer, _("Minimize"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "LOAD_EXTENSIONS_FAIL");
xmlTextWriterWriteString (writer, _("Program can't start because it failed to load the following module(s):"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "MENU_ITEM_ABOUT");
xmlTextWriterWriteString (writer, _("&About..."));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "MENU_ITEM_ADD_GADGETS");
xmlTextWriterWriteString (writer, _("Add &Gadgets..."));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "MENU_ITEM_ADD_IGOOGLE_GADGET");
xmlTextWriterWriteString (writer, _("Add an &iGoogle Gadget"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "MENU_ITEM_ALWAYS_ON_TOP");
xmlTextWriterWriteString (writer, _("Always on &Top"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "MENU_ITEM_AUTO_FIT");
xmlTextWriterWriteString (writer, _("Auto &Fit"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "MENU_ITEM_AUTO_HIDE");
xmlTextWriterWriteString (writer, _("A&uto Hide"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "MENU_ITEM_COLLAPSE");
xmlTextWriterWriteString (writer, _("&Collapse"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "MENU_ITEM_DOCK_TO_SIDEBAR");
xmlTextWriterWriteString (writer, _("&Dock to Sidebar"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "MENU_ITEM_DOCK_SIDEBAR");
xmlTextWriterWriteString (writer, _("Doc&k Sidebar"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "MENU_ITEM_EXIT");
xmlTextWriterWriteString (writer, _("E&xit"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "MENU_ITEM_EXPAND");
xmlTextWriterWriteString (writer, _("Ex&pand"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "MENU_ITEM_FONT_SIZE");
xmlTextWriterWriteString (writer, _("&Font Size"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "MENU_ITEM_FONT_SIZE_DEFAULT");
xmlTextWriterWriteString (writer, _("&Default"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "MENU_ITEM_FONT_SIZE_LARGER");
xmlTextWriterWriteString (writer, _("&Larger"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "MENU_ITEM_FONT_SIZE_SMALLER");
xmlTextWriterWriteString (writer, _("&Smaller"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "MENU_ITEM_HIDE_ALL");
xmlTextWriterWriteString (writer, _("Hide A&ll"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "MENU_ITEM_LEFT");
xmlTextWriterWriteString (writer, _("&Left"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "MENU_ITEM_OPTIONS");
xmlTextWriterWriteString (writer, _("&Options..."));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "MENU_ITEM_REMOVE");
xmlTextWriterWriteString (writer, _("R&emove"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "MENU_ITEM_RIGHT");
xmlTextWriterWriteString (writer, _("&Right"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "MENU_ITEM_SHOW_ALL");
xmlTextWriterWriteString (writer, _("Show A&ll"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "MENU_ITEM_UNDOCK_FROM_SIDEBAR");
xmlTextWriterWriteString (writer, _("&Undock from Sidebar"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "MENU_ITEM_ZOOM");
xmlTextWriterWriteString (writer, _("&Zoom"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "MENU_ITEM_100P");
xmlTextWriterWriteString (writer, _("100%"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "MENU_ITEM_125P");
xmlTextWriterWriteString (writer, _("125%"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "MENU_ITEM_150P");
xmlTextWriterWriteString (writer, _("150%"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "MENU_ITEM_175P");
xmlTextWriterWriteString (writer, _("175%"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "MENU_ITEM_200P");
xmlTextWriterWriteString (writer, _("200%"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "MENU_ITEM_50P");
xmlTextWriterWriteString (writer, _("50%"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "MENU_ITEM_75P");
xmlTextWriterWriteString (writer, _("75%"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "MENU_ITEM_CHANGE_HOTKEY");
xmlTextWriterWriteString (writer, _("Change &Hotkey..."));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "MENU_ITEM_DEBUG_CONSOLE");
xmlTextWriterWriteString (writer, _("De&bug Console"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "MENU_ITEM_SIDEBAR");
xmlTextWriterWriteString (writer, _("&Sidebar"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "MENU_ITEM_FEEDBACK");
xmlTextWriterWriteString (writer, _("Feedback..."));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "GADGET_CONFIRM_TITLE");
xmlTextWriterWriteString (writer, _("Third Party Gadget Installation"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "GADGET_CONFIRM_MESSAGE");
xmlTextWriterWriteString (writer, _("Google has not tested or verified the features or security of this third party Gadget. Please confirm that you want to install:"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "GADGET_DESCRIPTION");
xmlTextWriterWriteString (writer, _("Description: "));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "GADGET_REQUIRED_PERMISSIONS");
xmlTextWriterWriteString (writer, _("Required permissions: "));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "SCRIPT_BLOCKED_MESSAGE");
xmlTextWriterWriteString (writer, _("A script (%s:%d) on this gadget may be busy or have stopped responding. Do you want to stop it?"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "DEFAULT_HOTKEY_DIALOG_TITLE");
xmlTextWriterWriteString (writer, _("Change Hotkey"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "DEFAULT_HOTKEY_DIALOG_PROMPT");
xmlTextWriterWriteString (writer, _("Click to input the new hotkey:"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "HOTKEY_ENTRY_PROMPT");
xmlTextWriterWriteString (writer, _("Press new hotkey"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "CLEAR_HOTKEY");
xmlTextWriterWriteString (writer, _("Clear"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "HOTKEY_DISABLED");
xmlTextWriterWriteString (writer, _("Disabled"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "STATUS_ICON_TOOLTIP");
xmlTextWriterWriteString (writer, _("Gadgets"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "STATUS_ICON_TOOLTIP_WITH_HOTKEY");
xmlTextWriterWriteString (writer, _("Gadgets, press %s to show or hide gadgets."));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "DEBUG_CLEAR");
xmlTextWriterWriteString (writer, _("Clear"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "DEBUG_TRACE");
xmlTextWriterWriteString (writer, _("Trace"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "DEBUG_INFO");
xmlTextWriterWriteString (writer, _("Info"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "DEBUG_WARNING");
xmlTextWriterWriteString (writer, _("Warning"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "DEBUG_ERROR");
xmlTextWriterWriteString (writer, _("Error"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "DEBUG_LOCK_SCROLL");
xmlTextWriterWriteString (writer, _("Lock scroll"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "HOST_GTK_DESKTOP_NAME");
xmlTextWriterWriteString (writer, _("Gadgets (GTK)"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "HOST_QT_DESKTOP_NAME");
xmlTextWriterWriteString (writer, _("Gadgets (Qt)"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "GADGET_DESIGNER_NAME");
xmlTextWriterWriteString (writer, _("Gadget Designer"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "HOST_GTK_DESKTOP_COMMENT");
xmlTextWriterWriteString (writer, _("Run Gadgets in GNOME/GTK environment"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "HOST_QT_DESKTOP_COMMENT");
xmlTextWriterWriteString (writer, _("Run Gadgets in KDE/Qt environment"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "GADGET_DESIGNER_COMMENT");
xmlTextWriterWriteString (writer, _("Gadget Designer"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "PERMISSION_FILEREAD");
xmlTextWriterWriteString (writer, _("Reads content of local files and directories"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "PERMISSION_FILEWRITE");
xmlTextWriterWriteString (writer, _("Creates or modifies local files and directories"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "PERMISSION_DEVICESTATUS");
xmlTextWriterWriteString (writer, _("Queries or modifies the status of hardware devices"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "PERMISSION_NETWORK");
xmlTextWriterWriteString (writer, _("Accesses network"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "PERMISSION_PERSONALDATA");
xmlTextWriterWriteString (writer, _("Accesses personalization data"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "PERMISSION_ALLACCESS");
xmlTextWriterWriteString (writer, _("Executes native code and local applications"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "GADGET_LOAD_FAILURE");
xmlTextWriterWriteString (writer, _("The gadget could not be loaded:&#10;&#10;%s"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "GADGET_REQUIRE_API_VERSION");
xmlTextWriterWriteString (writer, _("The gadget requires Gadgets supporting API at least version %s:&#10;&#10;%s"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "GADGET_REQUIRE_HOST_VERSION");
xmlTextWriterWriteString (writer, _("The gadget requires Gadgets for Linux at least version %s:&#10;&#10;%s"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "GADGET_PLATFORM_NOT_SUPPORTED");
xmlTextWriterWriteString (writer, _("The gadget doesn't work on Linux platform:%&#10;&#10;%s"));
xmlTextWriterEndElement (writer);
xmlTextWriterStartElement (writer, "GOOGLE_HOMEPAGE_URL");
xmlTextWriterWriteString (writer, _("http://www.google.com"));
xmlTextWriterEndElement (writer);
 
  xmlTextWriterEndElement (writer); /* close strings */ 
  xmlTextWriterEndDocument(writer); 

  return 0; 
} 
